# Generated by Django 4.1.2 on 2023-01-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchinchanSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season', models.IntegerField(default=0)),
                ('Episodes', models.IntegerField(default=0)),
                ('Relise_Year', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShinchanMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Year', models.DateField(default=0)),
                ('IMDB', models.FloatField()),
                ('Cover', models.ImageField(upload_to='CoverPages')),
                ('Duration', models.IntegerField(default=0)),
            ],
        ),
    ]
